### ISSUE TITLE
Prepare QM v2.1 PS01

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#302]
**[WORKING DRAFT](https://oslc-op.github.io/oslc-specs/specs/qm/quality-management-spec.html)**

**Preflight**

- [x] Read the [guidelines](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#overall-process)
- [x] Notify the PGB of the _intent to publish_ ([template](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#pgb-notice-template), ask a PGB member if you are not on the board). The vote can be initiated at least 14 days after this letter has been sent.
- [x] Create a milestone for this stage ([link](https://github.com/oslc-op/oslc-specs/milestones?direction=asc&sort=due_date))
- [x] Add this issue to the newly created milestone and tag it "Kind: EPIC"
- [x] Search for all open issues and add the relevant ones to the milestone

**ReSpec & ShapeChecker**
- [x] Ensure latest ReSpec is used ([link](https://github.com/oasis-tcs/tab-respec/releases))
- [x] Ensure no critical ReSpec errors are present (see the ReSpec button in the top right corner)
- [x] Base URI updated to the OP archive (`docs.oasis-open-projects.org ` and not `docs.oasis-open.org ` unless it's for a _published_ previous stage)
- [x] `specStatus` set to the desired stage (PSD or higher)
- [x] `publishDate` set to the date of the PGB vote + 7 days (e.g. if you plan to open the vote on Mar 12, set it to Mar 19).
- [x] ShapeChecker is configured to check the shapes and vocabs (only if the spec publishes vocabs or shapes)
- [x] No ShapeChecker errors in the CircleCI build ([link](https://circleci.com/gh/oslc-op/oslc-specs))

**Editorial**

- [x] All issues in the milestone are resolved
- [x] RDF files (if any) have the license headers set correctly. NB! Do not put XML comments before the 2nd line; the first line must always be the XML declaration.
- [x] RDF files have correct metadata
- [x] No broken links other than the stage-to-be-published

> **NB!** Check links using https://addons.mozilla.org/en-GB/firefox/addon/find-broken-links/ (http://validator.w3.org/checklink if the PR for the spec did not touch the links since the last WD), fixing all broken links, and fixing those permanent redirects that appear sensible. **Do not** replace links for redirects from 'external' to 'internal' URIs - for example, never replace a link to `open-services.net/ns` with a link to a specific format or version of a vocabulary. Check accessibility using https://achecker.ca/checker/index.php, fixing issues that seem important

**OASIS**

- [x] Release Draft created (TODO add a hyperlink here to the Release Draft once created, create one [here](https://github.com/oslc-op/oslc-specs/releases))
- [x] Release ZIP uploaded ([instructions](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#release-zip-generation-steps), TODO add a hyperlink to the Release ZIP once created)
- [x] PGB notified the OP with a ZIP link
- [x] Spread the announcement on Slack and Lyo mailing lists
- [x] OASIS ballot request filed under [oasis-open-projects/administration](https://github.com/oasis-open-projects/administration/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen) (TODO add link)
- [x] OASIS opened a ballot
- [x] OASIS ballot closed
- [x] OASIS feedback addressed
- [x] The spec is published to the OASIS _staging_ archive
- [x] **The spec is published to the OASIS archive**

**After the publication**

- [x] Tag the commit that was used to produce published snapshots with `%shortname%-v%version%-%STAGE%%REVISION%`.
- [x] Promote the draft (pre-)release to a (pre-)release. _PSDs are pre-releases._
- [x] open-services.net redirects resolve to the current published specs/drafts (Andrew)
- [x] Add a new row to the https://github.com/oslc-op/website/edit/master/content/specifications/_index.md under Active publications with the link to the published spec
- [x] Move the old row (of the same version only) in the https://github.com/oslc-op/website/edit/master/content/specifications/_index.md from the Active publications to the Obsolete Publications table (DO NOT JUST DELETE AN OBSOLETE SPEC ROW!)
- [ ] open-services.net blog announcement (spec editor prepares a blog post, see [here](https://github.com/oslc-op/website/wiki/Creating-A-News-Post) and [there](https://github.com/oslc-op/website/wiki/Contributing-Setup), Andrew will do the deployment). The announcement will automatically appear on the forum.
- [ ] LinkedIn announcement (Axel)
- [ ] Twitter announcement (Andrew)

---

Issues in scope of this milestone:

- [Update PSD references to point to the latest revisions · Issue #257 · oslc-op/oslc-specs](https://github.com/oslc-op/oslc-specs/issues/257) 
- [QM title shall contain "Version" word · Issue #298 · oslc-op/oslc-specs](https://github.com/oslc-op/oslc-specs/issues/298)
- [QM/2 still has Previous Version · Issue #300 · oslc-op/oslc-specs](https://github.com/oslc-op/oslc-specs/issues/300)

Helpful links:

- [OASIS OP handbook](https://www.oasis-open.org/oasis-open-projects-handbook)
- [OSLC OP wiki page on the publication process](https://github.com/oslc-op/oslc-specs/wiki)
- [Work done in this milestone](https://github.com/oslc-op/oslc-specs/milestone/10?closed=1)

**Comment by berezovskyi** [comment]
https://github.com/oasis-open-projects/administration/issues/8#issuecomment-559553632

**Comment by berezovskyi** [comment]
I think with all the changes we shall go for PSD03 and then promote it to PS01 without any material changes.

**Comment by berezovskyi** [comment]
Notice of the ignored warnings:

- In Part 1 "Query MUST scope" conformance warnings found in the informative compatibility section, 1 warning was fixed. Thanks @ndjc!
- In Part 2 and Part 3 "conformance paragraph or table is required" error is not applicable. @jamsden or @ndjc if you have a suggestion, I will gladly take it.

**Comment by jamsden** [comment]
I used a blanket performance statement, and this eliminated the need to have conformance clauses from all the descriptions in the .ttl files - which I think might be noisy.

Shapes conformance:
```
    <section id="conformance">
      <h2>Conformance</h2>
      <p>
        Architecture Management servers MUST follow the constraints defined here where required, and with the meanings
        defined here.
      </p>
      <p>Architecture Management servers MAY provide additional constraints for specific purposes.</p>
    </section>
```
Vocab conformance:
```
    <section id="conformance">
      <h2>Conformance</h2>
      <p>
        Architecture Management servers MUST use the vocabulary terms defined here where required, and with the meanings
        defined here.
      </p>
      <p>
        Architecture Management servers MAY augment this vocabulary with additional classes, properties, and
        individuals.
      </p>
    </section>

```

**Comment by berezovskyi** [comment]
Release added under https://github.com/oslc-op/oslc-specs/releases/tag/untagged-c1483286e09fa573b673

**Comment by berezovskyi** [comment]
OP/PGB announcement made on https://lists.oasis-open-projects.org/g/oslc-op/message/316

OASIS admin issue opened on https://github.com/oasis-open-projects/administration/issues/11

**Comment by berezovskyi** [comment]
Tagged https://github.com/oslc-op/oslc-specs/releases/tag/qm-v2.1-ps01

Released https://github.com/oslc-op/oslc-specs/releases/tag/qm-v2.1-ps01

**Comment by berezovskyi** [comment]
https://open-services.net/specifications/ up to date

**Comment by berezovskyi** [comment]
Closing the epic and the milestone
