### ISSUE TITLE
Prepare RM v2.1 PS01

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#306]
**Preflight**

- [x] Read the [guidelines](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#overall-process)
- [x] Create a milestone for this stage ([link](https://github.com/oslc-op/oslc-specs/milestones?direction=asc&sort=due_date))
- [x] Add this issue to the newly created milestone and tag it "Kind: EPIC"
- [x] Search for all open issues and add the relevant ones to the milestone

**ReSpec & ShapeChecker**
- [x] CicleCI has Prettier configuration to check spec HTML correctness and formatting
- [x] CicleCI has ShapeChecker configuration to check shapes and vocabs
- [x] Ensure latest ReSpec is used ([link](https://github.com/oasis-tcs/tab-respec/releases))
- [x] Ensure no critical ReSpec errors are present (see the ReSpec button in the top right corner)
- [x] Base URI updated to the OP archive (`docs.oasis-open-projects.org ` and not `docs.oasis-open.org ` unless it's for a _published_ previous stage)
- [x] `specStatus` set to the desired stage (PSD or higher)
- [x] `publishDate` set to the date of the PGB vote + 7 days (e.g. if you plan to open the vote on Mar 12, set it to Mar 19).
- [x] No ShapeChecker errors in the CircleCI build ([link](https://circleci.com/gh/oslc-op/oslc-specs))

**Editorial**

- [x] All issues in the milestone are resolved
- [x] RDF files (if any) have the license headers set correctly. NB! Do not put XML comments before the 2nd line; the first line must always be the XML declaration.
- [x] No broken links other than the stage-to-be-published

> **NB!** Check links using https://addons.mozilla.org/en-GB/firefox/addon/find-broken-links/ (http://validator.w3.org/checklink if the PR for the spec did not touch the links since the last WD), fixing all broken links, and fixing those permanent redirects that appear sensible. **Do not** replace links for redirects from 'external' to 'internal' URIs - for example, never replace a link to `open-services.net/ns` with a link to a specific format or version of a vocabulary. Check accessibility using https://achecker.ca/checker/index.php, fixing issues that seem important

**OASIS**

- [x] Notify the PGB of the _intent to publish_ ([template](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#pgb-notice-template), ask a PGB member if you are not on the board). The vote can be initiated at least 14 days after this letter has been sent.
- [x] Release Draft created (TODO add a hyperlink here to the Release Draft once created, create one [here](https://github.com/oslc-op/oslc-specs/releases))
- [x] Release ZIP uploaded ([instructions](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#release-zip-generation-steps), TODO add a hyperlink to the Release ZIP once created)
- [x] OASIS publication request filed under [oasis-open-projects/administration](https://github.com/oasis-open-projects/administration/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen) (TODO add link)
- [x] PGB vote initiated ([template](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#pgb-ballot-template), TODO add date)
- [x] **PGB vote passed** (TODO add hyperlink to the announcement email)
- [x] OASIS feedback addressed
- [x] The spec is published to the OASIS _staging_ archive
- [x] OASIS review passed
- [x] **The spec is published to the OASIS archive**

**After the publication**

- [x] Tag the commit that was used to produce published snapshots with `%shortname%-v%version%-%STAGE%%REVISION%`.
- [x] Promote the draft (pre-)release to a (pre-)release. _PSDs are pre-releases._
- [x] open-services.net redirects resolve to the current published specs/drafts (Andrew)
- [x] Add a new row to the https://github.com/oslc-op/website/edit/master/content/specifications/_index.md under Active publications with the link to the published spec
- [x] Move the old row (of the same version only) in the https://github.com/oslc-op/website/edit/master/content/specifications/_index.md from the Active publications to the Obsolete Publications table (DO NOT JUST DELETE AN OBSOLETE SPEC ROW!)
- [ ] open-services.net blog announcement (spec editor prepares a blog post, see [here](https://github.com/oslc-op/website/wiki/Creating-A-News-Post) and [there](https://github.com/oslc-op/website/wiki/Contributing-Setup), Andrew will do the deployment). The announcement will automatically appear on the forum.
- [ ] LinkedIn announcement (Axel)
- [ ] Twitter announcement (Andrew)

**Comment by berezovskyi** [comment]
PSD publication issue: https://github.com/oasis-open-projects/administration/issues/5

**Comment by berezovskyi** [comment]
@jadelkhoury updated the instructions, feel free to edit the wiki or request help

**Comment by jadelkhoury** [comment]
@berezovskyi Can we go through this once, before I proceed?

I have now read the steps above, and I have a good idea of what needs to be done. Also have a good idea of what edits are needed for the RM specs. 
But of course I have questions.

**Comment by berezovskyi** [comment]
Published under https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/ps01/requirements-management-spec.html

**Comment by berezovskyi** [comment]
https://github.com/oasis-open-projects/administration/issues/12 closed

**Comment by berezovskyi** [comment]
tagged https://github.com/oslc-op/oslc-specs/releases/tag/rm-v2.1-ps01

**Comment by berezovskyi** [comment]
release published https://github.com/oslc-op/oslc-specs/releases/tag/rm-v2.1-ps01

**Comment by berezovskyi** [comment]
https://open-services.net/spec/rm/latest-draft and https://open-services.net/spec/rm/latest redirects verified

**Comment by berezovskyi** [comment]
https://github.com/oslc-op/website/edit/master/content/specifications/_index.md is up to date

**Comment by berezovskyi** [comment]
too late for twitter/linkedin promo, closing the issue and the milestone
