### ISSUE TITLE
Prepare Core v3.0 PS01

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#307]
**Preflight**

- [x] Read the [guidelines](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#overall-process)
- [x] **Notify the PGB of the _intent to publish_** ([template](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#pgb-notice-template), ask a PGB member if you are not on the board). The vote can be initiated at least 14 days after this letter has been sent.
- [x] Create a milestone for this stage ([link](https://github.com/oslc-op/oslc-specs/milestones?direction=asc&sort=due_date))
- [x] Add this issue to the newly created milestone and tag it "Kind: EPIC"
- [x] Search for all open issues and add the relevant ones to the milestone

**ReSpec & ShapeChecker**
- [x] CicleCI has Prettier configuration to check spec HTML correctness and formatting
- [x] CicleCI has ShapeChecker configuration to check shapes and vocabs
- [x] Ensure latest ReSpec is used ([link](https://github.com/oasis-tcs/tab-respec/releases))
- [x] Ensure no critical ReSpec errors are present (see the ReSpec button in the top right corner)
- [x] Base URI updated to the OP archive (`docs.oasis-open-projects.org ` and not `docs.oasis-open.org ` unless it's for a _published_ previous stage)
- [x] `specStatus` set to the desired stage (PSD or higher)
- [ ] `publishDate` set to the date of the PGB vote + 7 days (e.g. if you plan to open the vote on Mar 12, set it to Mar 19).
- [x] No ShapeChecker errors in the CircleCI build ([link](https://circleci.com/gh/oslc-op/oslc-specs))

**Editorial**

- [ ] All issues in the milestone are resolved
- [x] RDF files (if any) have the license headers set correctly. NB! Do not put XML comments before the 2nd line; the first line must always be the XML declaration.
- [x] No broken links other than the stage-to-be-published

> **NB!** Check links using https://addons.mozilla.org/en-GB/firefox/addon/find-broken-links/ (http://validator.w3.org/checklink if the PR for the spec did not touch the links since the last WD), fixing all broken links, and fixing those permanent redirects that appear sensible. **Do not** replace links for redirects from 'external' to 'internal' URIs - for example, never replace a link to `open-services.net/ns` with a link to a specific format or version of a vocabulary. Check accessibility using https://achecker.ca/checker/index.php, fixing issues that seem important

**OASIS**

- [ ] Release Draft created (TODO add a hyperlink here to the Release Draft once created, create one [here](https://github.com/oslc-op/oslc-specs/releases))
- [ ] Release ZIP uploaded ([instructions](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#release-zip-generation-steps), TODO add a hyperlink to the Release ZIP once created)
- [ ] PGB vote initiated ([template](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#pgb-ballot-template), TODO add date)
- [ ] **PGB vote passed** (TODO add hyperlink to the announcement email)
- [ ] OASIS publication request filed under [oasis-open-projects/administration](https://github.com/oasis-open-projects/administration/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen) (TODO add link)
- [ ] OASIS feedback addressed
- [ ] The spec is published to the OASIS _staging_ archive
- [ ] OASIS review passed
- [ ] **The spec is published to the OASIS archive**

**After the publication**

- [ ] Tag the commit that was used to produce published snapshots with `%shortname%-v%version%-%STAGE%%REVISION%`.
- [ ] Promote the draft (pre-)release to a (pre-)release. _PSDs are pre-releases._
- [ ] open-services.net redirects resolve to the current published specs/drafts (Andrew)
- [ ] open-services.net blog announcement (spec editor prepares a blog post, see [here](https://github.com/oslc-op/website/wiki/Creating-A-News-Post) and [there](https://github.com/oslc-op/website/wiki/Contributing-Setup), Andrew will do the deployment). The announcement will automatically appear on the forum.
- [ ] LinkedIn announcement (Axel)
- [ ] Twitter announcement (Andrew)

**Kitchensink (for the first-time publication under the Open Project)**

If this is the first PSD of the spec in the open project, there are many possible issues (accumulated from previous OASIS reviews). Please make a quick check to avoid having them and to speed up the review.

- [x] [ReSpec] `latestVersion` updated to point to the one for the OP, not the TC (only for the first PSD)
- [x] [ReSpec] `additionalArtifacts` links are relative
- [x] [OASIS/RM] in "Notices", the copyright year is missing - between "OASIS Open" and the period
- [x] [OASIS/RM] the links to the "Previous stage" should use http instead of https in this case, since the earlier files were installed with http links. When the HTML is retrieved using https, it is unable to load the associated .css file, so the document is poorly presented.
- [x] [OASIS/RM] add HTTPS to the image references
- [ ] [OASIS/RM] in Vocabulary, I would expect that the first two definition should be placed under 2.1.1, since they are Classes rather than Properties. See https://github.com/oasis-tcs/tab-respec/issues/17 (resolved by ReSpec 2.1.10)

**Comment by berezovskyi** [comment]
PSD publication: https://github.com/oasis-open-projects/administration/issues/9#issuecomment-574295981

**Comment by jamsden** [comment]
Here's my notes on what needs to be done to ready the core specs for PS01 (there may be some overlap with the items above:

- [ ] Review all open core issues and add any that need to be fixed in order to publish to milestone Core 3.0 PS01 issues addressed and need to be closed. Some changes might be needed, but there are no issues that need to be discussed.
- [ ] working group is still set as the OSLC TC - this should now be the "OSLC Open Project"
- [ ] Split vocab.html into separate vocabulary and shape specifications using the QM spec as a model
- [ ] add vocab and shape references in additional components sections in all multi-part documents
- [ ] add "Shape" suffix to all shape names.
- [ ] Shapes are all merged into one file, make sure the vocab and shapes documents read them properly
- [ ] Update respec version (see QM spec)
- [ ] Add conformance section to vocab and shapes documents. e.g., 
```
<section id='conformance'>
<h2>Conformance</h2>
<p>Configuration Management servers MUST use the vocabulary terms defined here where required,
and with the meanings defined here.</p>
<p>Configuration Management servers MAY augment this vocabulary with additional classes, properties,
and individuals. In particular, Configuration Management servers MAY define additional types of
configuration, but all configurations MUST also be of one of the types defined here.</p>
</section>
```
- [ ] Verify the metadata at top of the documents or in the config.json correct? (revision, spec Status, publishDate, previousPublishDate, etc.). Use QM spec as a guide
- [ ] Fix HTML errors, see https://app.circleci.com/pipelines/github/oslc-op/oslc-specs/389/workflows/03e08d5d-da5d-4622-8cbb-b09ddb8a0a52/jobs/385/parallel-runs/0/steps/0-104 
- [ ] To close issues automatically in a pull request, you must strictly follow the template: https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword. I edited the PR description for you.
- [ ] During the call last Thu we decided to create oslc:ShapeCollection resource to add metadata to the shape file. For the backstory see #325 (comment) and https://github.com/oslc-op/oslc-admin/blob/master/minutes/2020/2020-06-25.md#shapes-metadata
- [ ] Publish updated vocabulary and shapes files as part of the release zip file
The actual documents will be published by OASIS. We can use similar redirects from open-services.net to these documents that we use for the specs.
- [ ] Check links using  https://addons.mozilla.org/en-GB/firefox/addon/find-broken-links/  
Other then the localBiblio broken links, all good.

- [ ] The OSLCCore3 localBiblio links are broken:
http://open-services.net/specifications/core/oslc-core.html -> https://open-services.net/specifications/core/oslc-core.html
Should these be open-services.net redirects? https://open-services.net/spec/core/latest
But references to Core multi-part specifications don't have these redirects. 
Should Core have localBiblio references to itself or parts of its multi-part specification, or just replace those with relative links?
These are normative links.
In WD and PSD, localBiblio links are open-services.net latest, but when PS, use the one active at the time of publication is required, and the version should be included in the reference title

Remove all localBiblio references to core itself and replace them with relative links. There are only a couple of references.
This includes any reference to one of the core multi-part specifications in the localBiblio, but not references to query, config management, TRS or any other OSLC document that is not part of core multi-part specification and is published independently.
```
OSLCCore3
OSLCCoreVocab
ResourceShapes
OSLCPreview30
Dialogs

<a href=./oslc-core.html>OSLC Core Overview</a>
<a href="./resource-shape.html">ResourceShapes</a>
<a href="./core-vocab.html">OSLC Core vocabulary</a>
<a href="./resource-preview.html">OSLC Resource Preview</a>
<a href="./dialogs.html">Delegated dialogs</a>
```

**Comment by berezovskyi** [comment]
Fixed https://open-services.net/spec/core/latest-draft redirect

**Comment by berezovskyi** [comment]
milestone closed
