### ISSUE TITLE
Publish Query 3.0 PSD01

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#315]
**[WORKING DRAFT](https://oslc-op.github.io/oslc-specs/specs/query/oslc-query.html)**

**Preflight**

- [x] Read the [guidelines](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#overall-process)
- [x] **Notify the PGB of the _intent to publish_** ([template](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#pgb-notice-template), ask a PGB member if you are not on the board). The vote can be initiated at least 14 days after this letter has been sent.
- [x] Create a milestone for this stage ([link](https://github.com/oslc-op/oslc-specs/milestones?direction=asc&sort=due_date))
- [x] Add this issue to the newly created milestone
- [x] Search for all open issues and add the relevant ones to the milestone

**ReSpec & ShapeChecker**
- [x] Ensure latest ReSpec is used ([link](https://github.com/oasis-tcs/tab-respec/releases))
- [x] Ensure no critical ReSpec errors are present (see the ReSpec button in the top right corner)
- [x] Base URI updated to the OP archive (`docs.oasis-open-projects.org ` and not `docs.oasis-open.org ` unless it's for a _published_ previous stage)
- [x] `specStatus` set to the desired stage (PSD or higher)
- [x] `publishDate` set to the date of the PGB vote + 7 days (e.g. if you plan to open the vote on Mar 12, set it to Mar 19).
- [x] ShapeChecker is configured to check the shapes and vocabs (only if the spec publishes vocabs or shapes)
- [x] No ShapeChecker errors in the CircleCI build ([link](https://circleci.com/gh/oslc-op/oslc-specs))

**Editorial**

- [x] All issues in the milestone are resolved
- [x] RDF files (if any) have the license headers set correctly. NB! Do not put XML comments before the 2nd line; the first line must always be the XML declaration.
- [x] No broken links other than the stage-to-be-published

> **NB!** Check links using https://addons.mozilla.org/en-GB/firefox/addon/find-broken-links/ (http://validator.w3.org/checklink if the PR for the spec did not touch the links since the last WD), fixing all broken links, and fixing those permanent redirects that appear sensible. **Do not** replace links for redirects from 'external' to 'internal' URIs - for example, never replace a link to `open-services.net/ns` with a link to a specific format or version of a vocabulary. Check accessibility using https://achecker.ca/checker/index.php, fixing issues that seem important

**OASIS**

- [x] Release Draft created (TODO add a hyperlink here to the Release Draft once created, create one [here](https://github.com/oslc-op/oslc-specs/releases))
- [x] Release ZIP uploaded ([instructions](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#release-zip-generation-steps), TODO add a hyperlink to the Release ZIP once created)
- [x] PGB vote initiated ([template](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#pgb-ballot-template), 2020-06-26)
- [x] **PGB vote passed** (TODO add hyperlink to the announcement email)
- [x] OASIS publication request filed under [oasis-open-projects/administration](https://github.com/oasis-open-projects/administration/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen) (TODO add link)
- [x] OASIS feedback addressed
- [x] The spec is published to the OASIS _staging_ archive
- [x] OASIS review passed
- [x] **The spec is published to the OASIS archive**

**After the publication**

- [x] Tag the commit that was used to produce published snapshots with `%shortname%-v%version%-%STAGE%%REVISION%`.
- [x] Promote the draft (pre-)release to a (pre-)release. _PSDs are pre-releases._
- [x] open-services.net redirects resolve to the current published specs/drafts (Andrew)
- [x] Add a new row to the https://github.com/oslc-op/website/edit/master/content/specifications/_index.md under Active publications with the link to the published spec
- [x] Move the old row (of the same version only) in the https://github.com/oslc-op/website/edit/master/content/specifications/_index.md from the Active publications to the Obsolete Publications table (DO NOT JUST DELETE AN OBSOLETE SPEC ROW!)
- [ ] open-services.net blog announcement (spec editor prepares a blog post, see [here](https://github.com/oslc-op/website/wiki/Creating-A-News-Post) and [there](https://github.com/oslc-op/website/wiki/Contributing-Setup), Andrew will do the deployment). The announcement will automatically appear on the forum.
- [ ] LinkedIn announcement (Axel)
- [ ] Twitter announcement (Andrew)

**Kitchensink (for the first-time publication under the Open Project)**

If this is the first PSD of the spec in the open project, there are many possible issues (accumulated from previous OASIS reviews). Please make a quick check to avoid having them and to speed up the review.

- [x] [ReSpec] `latestVersion` updated to point to the one for the OP, not the TC (only for the first PSD)
- [x] [ReSpec] `additionalArtifacts` links are relative
- [x] [OASIS/RM] in "Notices", the copyright year is missing - between "OASIS Open" and the period
- [x] [OASIS/RM] the links to the "Previous stage" should use http instead of https in this case, since the earlier files were installed with http links. When the HTML is retrieved using https, it is unable to load the associated .css file, so the document is poorly presented.
- [x] [OASIS/RM] add HTTPS to the image references
- [x] [OASIS/RM] in Vocabulary, I would expect that the first two definition should be placed under 2.1.1, since they are Classes rather than Properties. See https://github.com/oasis-tcs/tab-respec/issues/17 (resolved by ReSpec 2.1.10)

**Comment by berezovskyi** [comment]
Just notified the PGB, the vote can be opened earliest March 26, with the publication date to be set earliest April 2.

**Comment by berezovskyi** [comment]
PGB vote initiated: https://lists.oasis-open-projects.org/g/oslc-op-pgb/topic/oslc_query_version_3_0_psd_01/75122018?p=,,,50,0,0,0::recentpostdate%2Fsticky,,,50,2,0,75122018

**Comment by berezovskyi** [comment]
Request for publication opened: https://github.com/oasis-open-projects/administration/issues/10

**Comment by berezovskyi** [comment]
please track https://github.com/oasis-open-projects/administration/issues/10 until closure

**Comment by berezovskyi** [comment]
https://github.com/oslc-op/oslc-specs/releases/tag/query-v3.0-psd01 has been published! Now let's finish up the remaining items.

**Comment by berezovskyi** [comment]
I did a forum announcement in the August OP summary
