### ISSUE TITLE
Publish AM PSD01

### ISSUE THREAD

**Issue by jamsden** [oslc-op/oslc-specs#419]
## EPIC checklist

**WORKING DRAFT:** https://oslc-op.github.io/oslc-specs/specs/am/architecture-management-spec.html  
**OASIS issue:** https://github.com/oasis-open-projects/administration/issues/15  
**Published spec:** https://docs.oasis-open-projects.org/oslc-op/am/v3.0/psd01/architecture-management-spec.html    

### Preflight

- [x] Read the [guidelines](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#overall-process)
- [x] **Notify the PGB of the _intent to publish_** ([template](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#pgb-notice-template), ask a PGB member if you are not on the board). The vote can be initiated at least 14 days after this letter has been sent.
- [x] Create a milestone for this stage ([link](https://github.com/oslc-op/oslc-specs/milestones?direction=asc&sort=due_date))
- [x] Add this issue to the newly created milestone and tag it "Kind: EPIC"
- [x] Search for all open issues and add the relevant ones to the milestone

### ReSpec & ShapeChecker 
- [x] CicleCI has Prettier configuration to check spec HTML correctness and formatting
    - install with `npm install -g prettier`
    -  Run `prettier --check specs/someFolder` to obtain list of errors to fix.
    -  Run `prettier --write specs/someFolder` to format the documents.
- [x] CicleCI has ShapeChecker configuration to check shapes and vocabs (**NB!** make sure `-C` flag is enabled to check shapes metadata)
- [x] Ensure latest ReSpec is used ([link](https://github.com/oasis-tcs/tab-respec/releases))
- [x] Ensure no critical ReSpec errors are present (see the ReSpec button in the top right corner)
    - run a local http server as instructed under https://github.com/oslc-op/oslc-specs#getting-started
    - browse to the html documents 
    - press the Respec button on the top right of each document to check.
- [x] Ensure no HTML errors are present in the spec draft (check via [W3C](https://validator.w3.org/nu/)) and also in the saved snapshot of every part of the spec (check via File Upload option of the W3C checker). _An exception has been made not to fix HTML5 errors that relate to dropped HTML table attributes._
- [x] Base URI updated to the OP archive (`docs.oasis-open-projects.org ` and not `docs.oasis-open.org ` unless it's for a _published_ previous stage). Look for "var oasisBase=".
- [x] `specStatus` set to the desired stage (PSD or higher)
- [x] `publishDate` set to the date of the PGB vote + 7 days (e.g. if you plan to open the vote on Mar 12, set it to Mar 19).
- [x] dcterms:issued in .ttl shapes and vocab files, set to same date as publishDate
- [x] dcterms:hasVersion in .ttl shapes and vocab files, set to specStatus+revision e.g,PSD01
- [x] dcterms:source and dcterms:isPartOf need to be changed to point to their future locations on open-services. See https://github.com/oslc-op/oslc-specs/pull/407/files, e.g., <https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/ps01/requirements-management-spec.html>
- [x] No ShapeChecker errors in the CircleCI build ([link](https://circleci.com/gh/oslc-op/oslc-specs))

### Editorial

- [x] All issues in the milestone are resolved
- [x] RDF files (if any) have the license headers set correctly. NB! Do not put XML comments before the 2nd line; the first line must always be the XML declaration.
- [x] No broken links other than the stage-to-be-published

> **NB!** Check links using https://addons.mozilla.org/en-GB/firefox/addon/find-broken-links/ (http://validator.w3.org/checklink if the PR for the spec did not touch the links since the last WD), fixing all broken links, and fixing those permanent redirects that appear sensible. **Do not** replace links for redirects from 'external' to 'internal' URIs - for example, never replace a link to `open-services.net/ns` with a link to a specific format or version of a vocabulary. Check accessibility using https://achecker.ca/checker/index.php, fixing issues that seem important

### OASIS

- [x] Release Draft created (TODO add a hyperlink here to the Release Draft once created, create one [here](https://github.com/oslc-op/oslc-specs/releases))
- [x] Release ZIP uploaded ([instructions](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#release-zip-generation-steps), TODO add a hyperlink to the Release ZIP once created)
- [x] PGB vote initiated ([template](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#pgb-ballot-template), TODO add date)
- [x] **PGB vote passed** (TODO add hyperlink to the announcement email)
- [x] OASIS publication request filed under [oasis-open-projects/administration](https://github.com/oasis-open-projects/administration/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen) (TODO add link)
- [x] OASIS feedback addressed
- [x] The spec is published to the OASIS _staging_ archive
- [x] OASIS review passed
- [x] **The spec is published to the OASIS archive**

### After the publication

- [x] Tag the commit that was used to produce published snapshots with `%shortname%-v%version%-%STAGE%%REVISION%`.
- [x] Promote the draft (pre-)release to a (pre-)release. _PSDs are pre-releases._
- [x] open-services.net redirects resolve to the current published specs/drafts (Andrew)
- [ ] open-services.net blog announcement (spec editor prepares a blog post, see [here](https://github.com/oslc-op/website/wiki/Creating-A-News-Post) and [there](https://github.com/oslc-op/website/wiki/Contributing-Setup), Andrew will do the deployment). The announcement will automatically appear on the forum.
- [ ] LinkedIn announcement (Axel)
- [ ] Twitter announcement (Andrew)

### Kitchensink (for the first-time publication under the Open Project)

If this is the first PSD of the spec in the open project, there are many possible issues (accumulated from previous OASIS reviews). Please make a quick check to avoid having them and to speed up the review.

- [x] [ReSpec] `latestVersion` updated to point to the one for the OP, not the TC (only for the first PSD)
- [x] [ReSpec] `additionalArtifacts` links are relative
- [x] [OASIS/RM] in "Notices", the copyright year is missing - between "OASIS Open" and the period
- [x] [OASIS/RM] the links to the "Previous stage" should use http instead of https in this case, since the earlier files were installed with http links. When the HTML is retrieved using https, it is unable to load the associated .css file, so the document is poorly presented.
- [x] [OASIS/RM] add HTTPS to the image references
- [x] [OASIS/RM] in Vocabulary, I would expect that the first two definition should be placed under 2.1.1, since they are Classes rather than Properties. See https://github.com/oasis-tcs/tab-respec/issues/17 (resolved by ReSpec 2.1.10)
- [x] [OASIS] make sure the WG name is "OASIS Open Services for Lifecycle Collaboration (OSLC) OP" (see https://github.com/oslc-op/oslc-specs/issues/221)

## Release ZIP generation steps

1. Run a local web server using `python3 -m http.server 8000` or `python -m SimpleHTTPServer 8000` or `npm install -g local-web-server` and then run `ws`. _Access from local filesystem may cause JS errors connected with security around local file access. You browser may render file and http protocols differently. DO NOT USE BROWSERSYNC AT THIS STAGE! **DO NOT SIMPLY OPEN FILES FROM THE FILESYSTEM, YOU MUST RUN A WEB SERVER!**_
1. Save the spec snapshot using Chrome in the Incognito mode in the HTML format. _This disables extensions that may affect the rendering of the spec._
1. Create a new folder.
1. Move all generated files.
1. **Copy all images and RDF files there too.**
1. **Check every file for HTML errors via https://validator.w3.org/nu/#file**
1. Zip up the directory.
1. Create a draft release/pre-release and attach the ZIP.
1. Link to the draft (pre-)release from the PR.

**Comment by berezovskyi** [comment]
Tag: https://github.com/oslc-op/oslc-specs/releases/tag/am-v3.0-psd01

**Comment by berezovskyi** [comment]
Links to https://open-services.net/spec/am/latest-draft and https://open-services.net/spec/am/latest updated

**Comment by berezovskyi** [comment]
Updated the spec table: https://github.com/oslc-op/website/commit/06379a20f7fbee09899ef3b31b807f71d406b880

**Comment by berezovskyi** [comment]
too late for the twitter and linkedin, closing this epic

**Comment by berezovskyi** [comment]
closed the milestone
