### ISSUE TITLE
Publish AM 3.0 PS 01

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#442]
- [x] Ensure PSD01 edits are carried over: https://github.com/oasis-open-projects/administration/issues/15#issuecomment-717380794

## EPIC checklist

**WORKING DRAFT**: https://oslc-op.github.io/oslc-specs/specs/am/architecture-management-spec.html
**OASIS issue:** https://issues.oasis-open.org/browse/TCADMIN-4064?jql=project%20%3D%20TCADMIN%20AND%20statusCategory%20!%3D%20Done%20%20ORDER%20BY%20key%20DESC%2C%20priority%20DESC%2C%20updated%20DESC
**Published spec:** N/A  

### Preflight

- [x] Read the [guidelines](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#overall-process)
- [x] Create a milestone for this stage ([link](https://github.com/oslc-op/oslc-specs/milestones?direction=asc&sort=due_date))
- [x] Add this issue to the newly created milestone and tag it "Kind: EPIC"
- [x] Search for all open issues and add the relevant ones to the milestone
- [ ] Reset the status to WD and publication date to "null". Push the changes to master and verify the draft webpage says "Working Draft ##" and does not have a date.
- [ ] Add the WD draft link to the top ☝️  (see https://github.com/oslc-op/oslc-specs#quick-links and update the table as well if needed)

### Spec text and ReSpec

- [x] Ensure latest ReSpec is used ([link](https://github.com/oasis-tcs/tab-respec/releases))
- [x] Remove `Part #:` from the titles of the Additional components for the vocabulary and shapes Turtle files. ([ref](https://github.com/oasis-open-projects/administration/issues/11#issuecomment-689722607), added 2020-09-09)
- [x] Make sure all URIs in the _Additional components_ are fully qualified ([ref](https://github.com/oasis-open-projects/administration/issues/11#issuecomment-689722607), added 2020-09-09)
- [x] head section contains a meta element with name="description" and content="{same text as in the abstract}"
- [ ] Update references to obsolete PSDs to point to the latest revisions. See https://open-services.net/specifications/ for a list of obsolete publications.
- [x] **All issues in the milestone are resolved**
- [x] Ensure no critical ReSpec errors (red) are present (see the ReSpec button in the top right corner)
    - run a local http server as instructed under https://github.com/oslc-op/oslc-specs#getting-started
    - browse to the html documents 
    - press the Respec button on the top right of each document to check.
- [x] `specStatus` set to the desired stage (PSD or higher)
- [x] `publishDate` set to the date of the PGB vote + 7 days (e.g. if you plan to open the vote on Mar 12, set it to Mar 19). Make sure to use the UTC timezone and set the time to 12:00 ([why](https://github.com/oasis-tcs/tab-respec/issues/57#issuecomment-879406570)), e.g. "2021-01-01T12:00Z".

### Machine readable RDF documents

- [ ] CicleCI has ShapeChecker configuration to check shapes and vocabs (**NB!** make sure `-C` flag is enabled to check shapes metadata). See under https://github.com/oslc-op/oslc-specs/tree/master/tools/ShapeChecker/scripts
- [x] RDF files (if any) have the license headers set correctly. NB! Do not put XML comments before the 2nd line; the first line must always be the XML declaration.
- [x] `dcterms:issued` in .ttl shapes and vocab files, set to same date as publishDate
- [x] `dcterms:hasVersion` in .ttl shapes and vocab files, set to specStatus+revision e.g,PSD01
- [x] `dcterms:source` and `dcterms:isPartOf` need to be changed to point to their future locations on open-services. See https://github.com/oslc-op/oslc-specs/pull/407/files, e.g., <https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/ps01/requirements-management-spec.html>

### OASIS

- [x] Create a snapshot from the specs and ZIP em up ([instructions](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#release-zip-generation-steps)
- [x] Ensure no HTML errors are present in the saved snapshot of every part of the spec (check via File Upload option of the W3C checker). _An exception has been made not to fix HTML5 errors that relate to dropped HTML table attributes._
- [x] No broken links other than the stage-to-be-published (cf. https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#overall-process)
- [x] Release Draft created (TODO add a hyperlink here to the Release Draft once created, create one [here](https://github.com/oslc-op/oslc-specs/releases))
- [x] Release ZIP uploaded, TODO add a hyperlink to the Release ZIP once created)
- [x] **Notify the PGB of the _intent to publish_** ([template](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#pgb-notice-template), ask a PGB member if you are not on the board). The vote can be initiated at least 14 days after this letter has been sent.
- [x] OASIS publication request filed under ~~[oasis-open-projects/administration](https://github.com/oasis-open-projects/administration/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)~~. New location is https://www.oasis-open.org/project-administration-support-requests/; search OASIS Jira for an automatically generated ticket. (Add the ticket link to the top ☝️)
- [x] PGB vote initiated ([template](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#pgb-ballot-template), TODO add date)
- [ ] PGB vote passed and Chet closed the ballot (TODO add hyperlink to the announcement email)
- [x] OASIS feedback addressed
- [ ] The spec is published to the OASIS _staging_ archive
- [ ] OASIS review passed
- [ ] **The spec is published to the OASIS archive** (Add the published link to the top ☝️)

### After the publication

- [ ] Tag the commit that was used to produce published snapshots with `%shortname%-v%version%-%STAGE%%REVISION%`.
- [ ] Promote the draft (pre-)release to a (pre-)release. _PSDs are pre-releases._
- [ ] Add a new row to the https://github.com/oslc-op/website/edit/master/content/specifications/_index.md under Active publications with the link to the published spec
- [ ] Move the old row (of the same version only) in the https://github.com/oslc-op/website/edit/master/content/specifications/_index.md from the Active publications to the Obsolete Publications table (DO NOT JUST DELETE AN OBSOLETE SPEC ROW!)
- [ ] open-services.net redirects resolve to the current published specs/drafts (ask Andrew, [info](https://github.com/oslc-op/cookbook/blob/master/README.md#adding-a-spec-redirect))
- [ ] open-services.net blog announcement (spec editor prepares a blog post, see [here](https://github.com/oslc-op/website/wiki/Creating-A-News-Post) and [there](https://github.com/oslc-op/website/wiki/Contributing-Setup), Andrew will do the deployment). The announcement will automatically appear on the forum.
- [ ] LinkedIn announcement (Axel)
- [ ] Twitter announcement (Andrew)

### Kitchensink (ONLY FOR THE FIRST PSD!)

If this is the first PSD of the spec in the open project, there are many possible issues (accumulated from previous OASIS reviews). Please make a quick check to avoid having them and to speed up the review.

- [ ] [ReSpec] Base URI updated to the OP archive (`docs.oasis-open-projects.org ` and not `docs.oasis-open.org ` unless it's for a _published_ previous stage). Look for "var oasisBase=".
- [ ] [ReSpec] `latestVersion` updated to point to the one for the OP, not the TC (only for the first PSD)
- [ ] [ReSpec] `additionalArtifacts` links are relative
- [ ] [OASIS/RM] in "Notices", the copyright year is missing - between "OASIS Open" and the period
- [ ] [OASIS/RM] the links to the "Previous stage" should use http instead of https in this case, since the earlier files were installed with http links. When the HTML is retrieved using https, it is unable to load the associated .css file, so the document is poorly presented.
- [ ] [OASIS/RM] add HTTPS to the image references
- [ ] [OASIS/RM] in Vocabulary, I would expect that the first two definition should be placed under 2.1.1, since they are Classes rather than Properties. See https://github.com/oasis-tcs/tab-respec/issues/17 (resolved by ReSpec 2.1.10)
- [ ] [OASIS] make sure the WG name is "OASIS Open Services for Lifecycle Collaboration (OSLC) OP" (see https://github.com/oslc-op/oslc-specs/issues/221)

**Comment by berezovskyi** [comment]
https://github.com/oasis-open-projects/administration/issues/15#issuecomment-717380794 closed 

https://docs.oasis-open-projects.org/oslc-op/am/v3.0/psd01/architecture-management-spec.html published

**Comment by berezovskyi** [comment]
### After the publication

- [ ] Tag the commit that was used to produce published snapshots with `%shortname%-v%version%-%STAGE%%REVISION%`.
- [ ] Promote the draft (pre-)release to a (pre-)release. _PSDs are pre-releases._
- [ ] open-services.net redirects resolve to the current published specs/drafts (ask Andrew, [info](https://github.com/oslc-op/cookbook/blob/master/README.md#adding-a-spec-redirect))
- [ ] Add a new row to the https://github.com/oslc-op/website/edit/master/content/specifications/_index.md under Active publications with the link to the published spec
- [ ] Move the old row (of the same version only) in the https://github.com/oslc-op/website/edit/master/content/specifications/_index.md from the Active publications to the Obsolete Publications table (DO NOT JUST DELETE AN OBSOLETE SPEC ROW!)
- [ ] open-services.net blog announcement (spec editor prepares a blog post, see [here](https://github.com/oslc-op/website/wiki/Creating-A-News-Post) and [there](https://github.com/oslc-op/website/wiki/Contributing-Setup), Andrew will do the deployment). The announcement will automatically appear on the forum.
- [ ] LinkedIn announcement (Axel)
- [ ] Twitter announcement (Andrew)

**Comment by berezovskyi** [comment]
https://open-services.net/spec/am/latest-draft and https://open-services.net/spec/am/latest resolve correctly

**Comment by berezovskyi** [comment]
I don't think the word Specification should be in the title.

**Comment by berezovskyi** [comment]
AM PSD approval: https://github.com/oslc-op/oslc-admin/blob/master/minutes-pgb/2020/2020-09-10.md

**Comment by berezovskyi** [comment]
PS SMV request: https://issues.oasis-open.org/browse/TCADMIN-4064?jql=project%20%3D%20TCADMIN%20AND%20statusCategory%20!%3D%20Done%20%20ORDER%20BY%20key%20DESC%2C%20priority%20DESC%2C%20updated%20DESC

**Comment by jamsden** [comment]
The other documents have a trailing identifier: vocabulary, constraints. CM use: OSLC Change Management Version 3.0. Part 1: Specification, when you remove the Part 1:, Specification is still there. I think it's fine.

**Comment by berezovskyi** [comment]
Oh, I see. But then I submitted the wrong title for the spec, right? It was the name of the first part instead.

**Comment by berezovskyi** [comment]
Verified that the latest links requested in https://github.com/oasis-open-projects/administration/issues/15#issuecomment-717380794 are fixed.

**Comment by frejfrej** [comment]
In architecture-management-spec.html, I believe there is a weirdness in the way we express the following:

> 2.9.3 Updating Multi-Valued Properties
> An OSLC AM Server MAY support updating a subset of a resource's properties by using the [LDPPatch] PATCH method. [AM-35]

This should not speak of "a subset of a resource's properties", but more likely "a multi-valued property".

**Comment by berezovskyi** [comment]
https://docs.oasis-open-projects.org/oslc-op/am/v3.0/architecture-management-spec.html
