### ISSUE TITLE
Publish Core 3.0 PS 02 & promote to OS

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#478]
**WORKING DRAFT:** https://oslc-op.github.io/oslc-specs/specs/core/oslc-core.html  
**OASIS issue:** https://issues.oasis-open.org/projects/TCADMIN/issues/TCADMIN-4056?filter=allopenissues

## Preflight

- [x] Read the [guidelines](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#overall-process)
- [x] Create a milestone for this stage ([link](https://github.com/oslc-op/oslc-specs/milestones?direction=asc&sort=due_date))
- [x] Add this issue to the newly created milestone and tag it "Kind: EPIC"
- [x] Search for all open issues and add the relevant ones to the milestone

## ReSpec & ShapeChecker 

- [x] CicleCI has ShapeChecker configuration to check shapes and vocabs (**NB!** make sure `-C` flag is enabled to check shapes metadata)
- [x] Ensure latest ReSpec is used ([link](https://github.com/oasis-tcs/tab-respec/releases))
- [x] Ensure no critical ReSpec errors are present (see the ReSpec button in the top right corner)
    - run a local http server as instructed under https://github.com/oslc-op/oslc-specs#getting-started
    - browse to the html documents 
    - press the Respec button on the top right of each document to check.

## Editorial

- [x] Make sure all URIs in the _Additional components_ are fully qualified ([ref](https://github.com/oasis-open-projects/administration/issues/11#issuecomment-689722607), added 2020-09-09)
- [x] RDF files (if any) have the license headers set correctly. NB! Do not put XML comments before the 2nd line; the first line must always be the XML declaration.
- [x] head section contains a meta element with name="description" and content="{same text as in the abstract}"
- [x] Remove `Part #:` from the titles of the Additional components for the vocabulary and shapes Turtle files. ([ref](https://github.com/oasis-open-projects/administration/issues/11#issuecomment-689722607), added 2020-09-09)
- [x] Update references to obsolete PSDs to point to the latest revisions. See https://open-services.net/specifications/ for a list of obsolete publications.
- [x] **All issues in the milestone are resolved**

## OASIS

- [x] `specStatus` set to the desired stage (PSD or higher)
- [x] `publishDate` set to the date of the PGB vote + 7 days (e.g. if you plan to open the vote on Mar 12, set it to Mar 19).
- [x] `dcterms:issued` in .ttl shapes and vocab files, set to same date as publishDate
- [x] `dcterms:hasVersion` in .ttl shapes and vocab files, set to specStatus+revision e.g,PSD01
- [x] `dcterms:source` and `dcterms:isPartOf` need to be changed to point to their future locations on open-services. See https://github.com/oslc-op/oslc-specs/pull/407/files, e.g., <https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/ps01/requirements-management-spec.html>
- [x] Create a snapshot from the specs and ZIP em up ([instructions](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#release-zip-generation-steps)
- [ ] No broken links other than the stage-to-be-published
- [ ] Ensure no HTML errors are present in the saved snapshot of every part of the spec (check via File Upload option of the W3C checker). _An exception has been made not to fix HTML5 errors that relate to dropped HTML table attributes._
- [x] Release Draft created (TODO add a hyperlink here to the Release Draft once created, create one [here](https://github.com/oslc-op/oslc-specs/releases))
- [x] Release ZIP uploaded, TODO add a hyperlink to the Release ZIP once created)
- [x] **Notify the PGB of the _intent to publish_** ([template](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#pgb-notice-template), ask a PGB member if you are not on the board). The vote can be initiated at least 14 days after this letter has been sent.
- [x] PGB vote initiated ([template](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#pgb-ballot-template), TODO add date)
- [x] **PGB vote passed** (TODO add hyperlink to the announcement email)
- [x] OASIS publication request filed under [oasis-open-projects/administration](https://github.com/oasis-open-projects/administration/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen) (TODO add link)
- [x] OASIS feedback addressed
- [x] The spec is published to the OASIS _staging_ archive
- [x] OASIS review passed
- [x] **The spec is published to the OASIS archive**

## After PS with COS changes

- [x] Tag the commit that was used to produce published snapshots with `%shortname%-v%version%-%STAGE%%REVISION%`.
- [x] Promote the draft (pre-)release to a (pre-)release. _PSDs are pre-releases._
- [x] open-services.net redirects resolve to the current published specs/drafts (Andrew)
- [x] Add a new row to the https://github.com/oslc-op/website/edit/master/content/specifications/_index.md under Active publications with the link to the published spec
- [x] Move the old row (of the same version only) in the https://github.com/oslc-op/website/edit/master/content/specifications/_index.md from the Active publications to the Obsolete Publications table (DO NOT JUST DELETE AN OBSOLETE SPEC ROW!)

## After OS

- [ ] Submit a permanent IANA application
- [ ] Update the NS publication
- [ ] Tag the commit that was used to produce published snapshots with `%shortname%-v%version%-%STAGE%%REVISION%`.
- [ ] Promote the draft (pre-)release to a (pre-)release. _PSDs are pre-releases._
- [ ] open-services.net redirects resolve to the current published specs/drafts (Andrew)
- [ ] Add a new row to the https://github.com/oslc-op/website/edit/master/content/specifications/_index.md under Active publications with the link to the published spec
- [ ] Move the old row (of the same version only) in the https://github.com/oslc-op/website/edit/master/content/specifications/_index.md from the Active publications to the Obsolete Publications table (DO NOT JUST DELETE AN OBSOLETE SPEC ROW!)
- [ ] open-services.net blog announcement (spec editor prepares a blog post, see [here](https://github.com/oslc-op/website/wiki/Creating-A-News-Post) and [there](https://github.com/oslc-op/website/wiki/Contributing-Setup), Andrew will do the deployment). The announcement will automatically appear on the forum.
- [ ] LinkedIn announcement (Axel)
- [ ] Twitter announcement (Andrew)

## Kitchensink (for the first-time publication under the Open Project)

If this is the first PSD of the spec in the open project, there are many possible issues (accumulated from previous OASIS reviews). Please make a quick check to avoid having them and to speed up the review.

- [ ] [ReSpec] `latestVersion` updated to point to the one for the OP, not the TC (only for the first PSD)
- [ ] [ReSpec] `additionalArtifacts` links are relative
- [ ] [OASIS/RM] in "Notices", the copyright year is missing - between "OASIS Open" and the period
- [ ] [OASIS/RM] the links to the "Previous stage" should use http instead of https in this case, since the earlier files were installed with http links. When the HTML is retrieved using https, it is unable to load the associated .css file, so the document is poorly presented.
- [ ] [OASIS/RM] add HTTPS to the image references
- [ ] [OASIS/RM] in Vocabulary, I would expect that the first two definition should be placed under 2.1.1, since they are Classes rather than Properties. See https://github.com/oasis-tcs/tab-respec/issues/17 (resolved by ReSpec 2.1.10)
- [ ] [OASIS] make sure the WG name is "OASIS Open Services for Lifecycle Collaboration (OSLC) OP" (see https://github.com/oslc-op/oslc-specs/issues/221)

**Comment by berezovskyi** [comment]
ReSpec warnings:

- [ ] part 2 / 8 warnings
- [ ] part 3 / **34 warnings**
- [ ] part 5 / 1 warning
- [ ] part 6 / 1 warning
- [ ] part 7 / **19 warnings**
- [ ] part 8 / **20 warnings**

Vocab warnings:

- [ ] https://github.com/oslc-op/oslc-specs/issues/343

**Comment by berezovskyi** [comment]
@jamsden I need your confirmation that "contexts" and "schema" directories under https://github.com/oslc-op/oslc-specs/tree/master/specs/core should be in the OS package, please.

**Comment by berezovskyi** [comment]
My preliminary analysis is that those files are both used to generate `resource-preview.html` but are not part of the package for publication.

**Comment by jamsden** [comment]
Yes, these are referenced in the document. They're separate files for convenience of creating and editing the content.

**Comment by berezovskyi** [comment]
Package uploaded to https://issues.oasis-open.org/projects/TCADMIN/issues/TCADMIN-4056?filter=allopenissues

**Comment by berezovskyi** [comment]
Tagged 49ed35d67a9020728d7a1ad694be01d64d5c8d00 as `core-v3.0-ps02`

**Comment by berezovskyi** [comment]
Core is OS now
