### ISSUE TITLE
Publish oslc-config-mgmt version 1.0 PSD01

### ISSUE THREAD

**Issue by jamsden** [oslc-op/oslc-specs#531]
## EPIC checklist

**WORKING DRAFT**: N/A  
**OASIS issue:** N/A  
**Published spec:** N/A  

### Preflight

- [ ] Read the [guidelines](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#overall-process)
- [ ] Create a milestone for this stage ([link](https://github.com/oslc-op/oslc-specs/milestones?direction=asc&sort=due_date))
- [ ] Add this issue to the newly created milestone and tag it "Kind: EPIC"
- [ ] Search for all open issues and add the relevant ones to the milestone
- [ ] Reset the status to WD and publication date to "null". Push the changes to master and verify the draft webpage says "Working Draft ##" and does not have a date.
- [ ] Add the WD draft link to the top ☝️  (see https://github.com/oslc-op/oslc-specs#quick-links and update the table as well if needed)

### Spec text and ReSpec

- [ ] Ensure latest ReSpec is used ([link](https://github.com/oasis-tcs/tab-respec/releases))
- [ ] Remove `Part #:` from the titles of the Additional components for the vocabulary and shapes Turtle files. ([ref](https://github.com/oasis-open-projects/administration/issues/11#issuecomment-689722607), added 2020-09-09)
- [ ] Make sure all URIs in the _Additional components_ are fully qualified ([ref](https://github.com/oasis-open-projects/administration/issues/11#issuecomment-689722607), added 2020-09-09)
- [ ] head section contains a meta element with name="description" and content="{same text as in the abstract}"
- [ ] Update references to obsolete PSDs to point to the latest revisions. See https://open-services.net/specifications/ for a list of obsolete publications.
- [ ] **All issues in the milestone are resolved**
- [ ] Ensure no critical ReSpec errors (red) are present (see the ReSpec button in the top right corner)
    - run a local http server as instructed under https://github.com/oslc-op/oslc-specs#getting-started
    - browse to the html documents 
    - press the Respec button on the top right of each document to check.
- [ ] `specStatus` set to the desired stage (PSD or higher)
- [ ] `publishDate` set to the date of the PGB vote + 7 days (e.g. if you plan to open the vote on Mar 12, set it to Mar 19). Make sure to use the UTC timezone and set the time to 12:00 ([why](https://github.com/oasis-tcs/tab-respec/issues/57#issuecomment-879406570)), e.g. "2021-01-01T12:00Z".

### Machine readable RDF documents

- [ ] CicleCI has ShapeChecker configuration to check shapes and vocabs (**NB!** make sure `-C` flag is enabled to check shapes metadata). See under https://github.com/oslc-op/oslc-specs/tree/master/tools/ShapeChecker/scripts
- [ ] RDF files (if any) have the license headers set correctly. NB! Do not put XML comments before the 2nd line; the first line must always be the XML declaration.
- [ ] `dcterms:issued` in .ttl shapes and vocab files, set to same date as publishDate
- [ ] `dcterms:hasVersion` in .ttl shapes and vocab files, set to specStatus+revision e.g,PSD01
- [ ] `dcterms:source` and `dcterms:isPartOf` need to be changed to point to their future locations on open-services. See https://github.com/oslc-op/oslc-specs/pull/407/files, e.g., <https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/ps01/requirements-management-spec.html>

### OASIS

- [ ] Create a snapshot from the specs and ZIP em up ([instructions](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#release-zip-generation-steps)
- [ ] Ensure no HTML errors are present in the saved snapshot of every part of the spec (check via File Upload option of the W3C checker). _An exception has been made not to fix HTML5 errors that relate to dropped HTML table attributes._
- [ ] No broken links other than the stage-to-be-published (cf. https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#overall-process)
- [ ] Release Draft created (TODO add a hyperlink here to the Release Draft once created, create one [here](https://github.com/oslc-op/oslc-specs/releases))
- [ ] Release ZIP uploaded, TODO add a hyperlink to the Release ZIP once created)
- [ ] **Notify the PGB of the _intent to publish_** ([template](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#pgb-notice-template), ask a PGB member if you are not on the board). The vote can be initiated at least 14 days after this letter has been sent.
- [ ] OASIS publication request filed under [oasis-open-projects/administration](https://github.com/oasis-open-projects/administration/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen) (Add the ticket link to the top ☝️)
- [ ] PGB vote initiated ([template](https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines#pgb-ballot-template), TODO add date)
- [ ] PGB vote passed and Chet closed the ballot (TODO add hyperlink to the announcement email)
- [ ] OASIS feedback addressed
- [ ] The spec is published to the OASIS _staging_ archive
- [ ] OASIS review passed
- [ ] **The spec is published to the OASIS archive** (Add the published link to the top ☝️)

### After the publication

- [ ] Tag the commit that was used to produce published snapshots with `%shortname%-v%version%-%STAGE%%REVISION%`.
- [ ] Promote the draft (pre-)release to a (pre-)release. _PSDs are pre-releases._
- [ ] Add a new row to the https://github.com/oslc-op/website/edit/master/content/specifications/_index.md under Active publications with the link to the published spec
- [ ] Move the old row (of the same version only) in the https://github.com/oslc-op/website/edit/master/content/specifications/_index.md from the Active publications to the Obsolete Publications table (DO NOT JUST DELETE AN OBSOLETE SPEC ROW!)
- [ ] open-services.net redirects resolve to the current published specs/drafts (ask Andrew, [info](https://github.com/oslc-op/cookbook/blob/master/README.md#adding-a-spec-redirect))
- [ ] open-services.net blog announcement (spec editor prepares a blog post, see [here](https://github.com/oslc-op/website/wiki/Creating-A-News-Post) and [there](https://github.com/oslc-op/website/wiki/Contributing-Setup), Andrew will do the deployment). The announcement will automatically appear on the forum.
- [ ] LinkedIn announcement (Axel)
- [ ] Twitter announcement (Andrew)

### Kitchensink (ONLY FOR THE FIRST PSD!)

If this is the first PSD of the spec in the open project, there are many possible issues (accumulated from previous OASIS reviews). Please make a quick check to avoid having them and to speed up the review.

- [ ] [ReSpec] Base URI updated to the OP archive (`docs.oasis-open-projects.org ` and not `docs.oasis-open.org ` unless it's for a _published_ previous stage). Look for "var oasisBase=".
- [ ] [ReSpec] `latestVersion` updated to point to the one for the OP, not the TC (only for the first PSD)
- [ ] [ReSpec] `additionalArtifacts` links are relative
- [ ] [OASIS/RM] in "Notices", the copyright year is missing - between "OASIS Open" and the period
- [ ] [OASIS/RM] the links to the "Previous stage" should use http instead of https in this case, since the earlier files were installed with http links. When the HTML is retrieved using https, it is unable to load the associated .css file, so the document is poorly presented.
- [ ] [OASIS/RM] add HTTPS to the image references
- [ ] [OASIS/RM] in Vocabulary, I would expect that the first two definition should be placed under 2.1.1, since they are Classes rather than Properties. See https://github.com/oasis-tcs/tab-respec/issues/17 (resolved by ReSpec 2.1.10)
- [ ] [OASIS] make sure the WG name is "OASIS Open Services for Lifecycle Collaboration (OSLC) OP" (see https://github.com/oslc-op/oslc-specs/issues/221)

**Comment by berezovskyi** [comment]
Ah, and we should also use the new logo Paul emailed us a link to a short while ago.

**Comment by berezovskyi** [comment]
But we can fix it at the publication.

**Comment by jamsden** [comment]
Is this a ReSpec issue not config? The config sources files don't seem to reference the OSLC icon directly. Or better OASIS simply updates the icon based on this ReSpec generated href:
```
<a href="https://www.oasis-open.org/" target="_blank"><img width="50%" src="https://docs.oasis-open-projects.org/templates/logo/open-projects-logo.png" alt="OASIS Open Projects" border="0"></a>
```

**Comment by berezovskyi** [comment]
Vote has passed: https://lists.oasis-open-projects.org/g/oslc-op-pgb/topic/85165193#181

OASIS ticket to publish: https://issues.oasis-open.org/browse/TCADMIN-4061

**Comment by berezovskyi** [comment]
@jamsden Paul left comments in [TCADMIN-4061](https://issues.oasis-open.org/projects/TCADMIN/issues/TCADMIN-4061?filter=allopenissues) that need to be fixed before the publication:

- [ ] The titles of the documents don't follow the [OASIS Naming Directives](http://docs.oasis-open.org/specGuidelines/ndr/namingDirectives.html#WorkProduct-Title), which require:
  - [ ] the word "Version" before the version number, and (for multiple Parts) a period after the number.
  - [ ] the word "Part" followed by a numeral and colon before the title of individual prose parts. 
- [ ] Instead of "OSLC Configuration Management 1.0: Overview", etc., the titles should be:
  - [ ] "OSLC Configuration Management Version 1.0. Part 1: Overview"
  - [ ] "OSLC Configuration Management Version 1.0. Part 2: Versioned Resources"
  - [ ] "OSLC Configuration Management Version 1.0. Part 3: Configuration Specification"
  - [ ] "OSLC Configuration Management Version 1.0. Part 4: RDF Vocabulary"
- [ ] in "Configuration Specification", the citation for [OSLCCore3] points to open-services.net, where it is apparently redirected to the published OSLC OP document. It should just point to the OSLC OP document in the OASIS OP Library. _The recommended citation would be:
OSLC Core Version 3.0. Part 1: Overview. Edited by Jim Amsden and Andrii Berezovskyi. Latest stage: https://docs.oasis-open-projects.org/oslc-op/core/v3.0/oslc-core.html._
- [ ] in "Configuration Specification", the citation for [OSLCQuery] has a URI for open-services.net, but it is broken. _The recommended citation would be:
OSLC Query Version 3.0. Edited by Jim Amsden and David Honey. Latest stage: https://docs.oasis-open-projects.org/oslc-op/query/v3.0/oslc-query.html._
- [ ] "Versioned Resources", reference to [TRS] can now use the published OASIS document:
"OSLC Tracked Resource Set Version 3.0. Part 1: Specification. Edited by Nick Crossley. Latest stage: https://docs.oasis-open-projects.org/oslc-op/trs/v3.0/tracked-resource-set.html."

**Comment by berezovskyi** [comment]
@jamsden will you be able to fix these ☝️ so that we can submit an IANA application soon, please?

**Comment by berezovskyi** [comment]
https://github.com/oslc-op/oslc-specs/releases/tag/config-v1.0-psd01

**Comment by berezovskyi** [comment]
Wrong (but valid) ticket for the broken links: https://github.com/oslc-op/oslc-specs/issues/547
